### ISSUE TITLE
Fundamental Styles 0.4.0 Adaptation

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-ngx#1756]
Since there is 0.4.0 version, we should make some changes in our code following [breaking changes](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#040)

* [x] Add busy indicator component https://github.com/SAP/fundamental-ngx/issues/1699
* [x] Check if items are aligned correctly https://github.com/SAP/fundamental-ngx/issues/1713
* [x] Radio adapt https://github.com/SAP/fundamental-ngx/issues/1757 https://github.com/SAP/fundamental-ngx/issues/1716 https://github.com/SAP/fundamental-ngx/issues/1714
* [x] Checkbox adapt https://github.com/SAP/fundamental-ngx/issues/1769
* [x] Alert component adapt https://github.com/SAP/fundamental-ngx/issues/1758
