### ISSUE TITLE
Defect Hunting - April 13-14 - version 0.16

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2334]
The result of defect hunting - April 13-14 - version 0.16

- [x] Select vs. Select Native -> transferred to https://github.com/SAP/fundamental-styles/issues/872
![Screen Shot 2020-04-13 at 2 39 11 PM](https://user-images.githubusercontent.com/4380815/79149099-9a904780-7d94-11ea-80d9-b183d1c00db2.png)
![Screen Shot 2020-04-13 at 2 39 06 PM](https://user-images.githubusercontent.com/4380815/79149103-9b28de00-7d94-11ea-8860-c01273dd67f3.png)
- [x] Status Indicator LTR vs. RTL - deprecated
![Screen Shot 2020-04-13 at 2 43 49 PM](https://user-images.githubusercontent.com/4380815/79149482-3a4dd580-7d95-11ea-881a-5351932147a3.png)
**It is broken in styles**
![image](https://user-images.githubusercontent.com/10849982/79216583-b60b5900-7e4d-11ea-9a78-530e952ba768.png)

![Screen Shot 2020-04-13 at 2 43 45 PM](https://user-images.githubusercontent.com/4380815/79149484-3a4dd580-7d95-11ea-802e-435e1c508869.png)
- [x] Side Navigation LRT vs. RTL - addressed in https://github.com/SAP/fundamental-styles/issues/873
![Screen Shot 2020-04-13 at 2 49 00 PM](https://user-images.githubusercontent.com/4380815/79149968-f9a28c00-7d95-11ea-8315-ade4fff71eb6.png)
![Screen Shot 2020-04-13 at 2 48 43 PM](https://user-images.githubusercontent.com/4380815/79149969-fa3b2280-7d95-11ea-993f-513d01fcd6a8.png)
**It has to be fixed in styles**
![image](https://user-images.githubusercontent.com/10849982/79218693-1e0f6e80-7e51-11ea-8f81-e64b9c8b0366.png)

- [x] shellbar and side navigation (hamburger menu) and box shadows LRT vs. RTL - Jedrzej **IN PR** https://github.com/SAP/fundamental-ngx/pull/2345 and in https://github.com/SAP/fundamental-styles/issues/873
![Screen Shot 2020-04-13 at 2 51 29 PM](https://user-images.githubusercontent.com/4380815/79150226-5e5de680-7d96-11ea-918b-0dfc9029c9f3.png)
![Screen Shot 2020-04-13 at 2 51 23 PM](https://user-images.githubusercontent.com/4380815/79150227-5ef67d00-7d96-11ea-89ea-4519738e7a79.png)

- [x] Shellbar + product switch - button background color and RTL - Jedrzej **IN PR** https://github.com/SAP/fundamental-ngx/pull/2346
![Screen Shot 2020-04-13 at 2 54 23 PM](https://user-images.githubusercontent.com/4380815/79150422-c14f7d80-7d96-11ea-870f-c44b654c3132.png)
![Screen Shot 2020-04-13 at 2 54 23 PM](https://user-images.githubusercontent.com/4380815/79150433-c57b9b00-7d96-11ea-97aa-154763d3429f.png)
- [x] Date Picker and Date Time Picker focus trap doesn't work when the user presses Shift + Tab instead of Tab
- [x] form message in combobox is missing the padding in RTL - addressed in https://github.com/SAP/fundamental-styles/issues/874
![Screen Shot 2020-04-13 at 3 24 51 PM](https://user-images.githubusercontent.com/4380815/79152911-02e22780-7d9b-11ea-8958-53d6a25c3d62.png)
![Screen Shot 2020-04-13 at 3 24 43 PM](https://user-images.githubusercontent.com/4380815/79152937-0d042600-7d9b-11ea-9794-405fe9817da5.png)
- [x] TimePicker button has double border - #2341
![Screen Shot 2020-04-13 at 2 40 37 PM](https://user-images.githubusercontent.com/4380815/79149207-cc091300-7d94-11ea-822f-bc8b7f428168.png)
- [x] Radio Button LRT vs. RTL
![Screen Shot 2020-04-13 at 2 53 27 PM](https://user-images.githubusercontent.com/4380815/79150336-96652980-7d96-11ea-90ab-b98917b4d1b6.png) fixed #2337
![Screen Shot 2020-04-13 at 2 53 21 PM](https://user-images.githubusercontent.com/4380815/79150337-96fdc000-7d96-11ea-88f9-1382e63a8e7d.png)
- [x] multi input button - double border - #2341
![Screen Shot 2020-04-13 at 3 08 05 PM](https://user-images.githubusercontent.com/4380815/79151582-b0077080-7d98-11ea-9f91-a55fac112590.png)
- [x] input group with button has double border - #2341
![Screen Shot 2020-04-13 at 3 11 13 PM](https://user-images.githubusercontent.com/4380815/79151779-112f4400-7d99-11ea-94d9-3a9d976ebbc1.png)
- [x] input group with complex template - **Cannot Reproduce**
![Screen Shot 2020-04-13 at 3 12 48 PM](https://user-images.githubusercontent.com/4380815/79151905-4b98e100-7d99-11ea-9750-e1b825467305.png)
 - [x] Combobox button has double borders - #2341
![Screen Shot 2020-04-13 at 3 16 42 PM](https://user-images.githubusercontent.com/4380815/79152232-d4178180-7d99-11ea-912b-87a931d94ded.png)
- [x] deprecate: Loading Spinner, Status Indicator
