### ISSUE TITLE
Defect Hunting July 11, 2020

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#2837]
List of issues in NGX:

- [ ] combobox highlighting issue - [#2838](https://github.com/SAP/fundamental-ngx/issues/2838)

- [ ] Menu Flashes in IE11 - [#2839](https://github.com/SAP/fundamental-ngx/issues/2839)

- [ ] Toolbar issues - [#2836](https://github.com/SAP/fundamental-ngx/issues/2836)

- [x] Schematics error - [#2835](https://github.com/SAP/fundamental-ngx/issues/2835)

- [ ] npm package looks too big [#2864](https://github.com/SAP/fundamental-ngx/issues/2854)
