### ISSUE TITLE
Defect Hunting Fundamental NGX 0.22

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3085]
Test the library and the doc website.
List the issues here:
- [x] **Core**-Combobox: on page load console displays below error. [#3191](https://github.com/SAP/fundamental-ngx/pull/3191)
 
```
     main.js:24086 ERROR Error: Multiple components match node with tagname fd-combobox
    at throwMultipleComponentError (main.js:25668)
```

- [x] **Core**-table  : on page load console displays below error.[#3191](https://github.com/SAP/fundamental-ngx/pull/3191)
`main.js:24086 ERROR Error: The pipe ‘filter’ could not be found!`

- [x] **Core**-file-uploader : on page load console displays logs. - https://github.com/SAP/fundamental-ngx/pull/3207

- [x] **Core**-Select-native  : on page load console displays below error. [#3191](https://github.com/SAP/fundamental-ngx/pull/3191)

```
main.js:24086 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: ‘core/select-native’
Error: Cannot match any routes. URL Segment: ‘core/select-native’
```

- [x] **Core**-Input group : on page load console displays below error.[#3191](https://github.com/SAP/fundamental-ngx/pull/3191)
```
 Error: Multiple components match node with tagname fd-input-group
    at throwMultipleComponentError (main.js:25668)
    at findDirectiveDefMatches (main.js:29137)
    at resolveDirectives (main.js:28883)
    at elementStartFirstCreatePass (main.js:36219)
```

**Comment by sKudum** [comment]
- [ ] Combobox(Core) : on page load console displays below error.
        ```
main.js:24086 ERROR Error: Multiple components match node with tagname fd-combobox
    at throwMultipleComponentError (main.js:25668)
```

- [ ] file-uploader(Core) : on page load console displays logs.

- [ ] Input group(Core) : on page load console displays below error.
```
 Error: Multiple components match node with tagname fd-input-group
    at throwMultipleComponentError (main.js:25668)
    at findDirectiveDefMatches (main.js:29137)
    at resolveDirectives (main.js:28883)
    at elementStartFirstCreatePass (main.js:36219) 
```

- [ ] Select-native (Core) : on page load console displays below error.
```
main.js:24086 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: ‘core/select-native’
Error: Cannot match any routes. URL Segment: ‘core/select-native’
```

- [ ] table (Core) : on page load console displays below error.
`main.js:24086 ERROR Error: The pipe ‘filter’ could not be found!`

**Comment by DeepakSap14** [comment]
- [ ] File uploder:
This is form input component. but it is missing [state] property to set the field validation status.

**Comment by puru-hk** [comment]
File Uploader: Drag and drop functionality is not working. 

[Darg and drop is not working.zip](https://github.com/SAP/fundamental-ngx/files/5175169/Darg.and.drop.is.not.working.zip)

**Comment by JKMarkowski** [comment]
- [ ] Image not loaded:
![image](https://user-images.githubusercontent.com/26483208/92362369-3332b580-f0f0-11ea-89a0-3a969451bd99.png)

- [ ] Performance issues on calendar
![calendarperformance](https://user-images.githubusercontent.com/26483208/92362670-9d4b5a80-f0f0-11ea-9e44-35fdeafb6618.gif)

- [ ] Combobox - pressing enter doesn't change value
![combboxenter](https://user-images.githubusercontent.com/26483208/92362893-f61af300-f0f0-11ea-9dba-c9bacf6fc2a8.gif)

- [ ] datepicker/calendar/datetimepicker wrong segmented button usage -
![image](https://user-images.githubusercontent.com/26483208/92363008-1cd92980-f0f1-11ea-8c33-e0d5093bff07.png)


- [ ] pickers - clicking on input shouldn't open popover

- [ ] input group page 
![image](https://user-images.githubusercontent.com/26483208/92363525-e819a200-f0f1-11ea-88e8-95dc8a007037.png)

- [ ] multi input doesn't work properly with space/clicking
![multiinput](https://user-images.githubusercontent.com/26483208/92363781-56f6fb00-f0f2-11ea-8392-becd5f4efa5d.gif)

**Comment by JKMarkowski** [comment]
- [ ] datepicker/datetimepicker/timepicker - change examples with properly displayed messages (like on combobox, top of popover body)

**Comment by JKMarkowski** [comment]
- [ ] icons inside tabs 
![image](https://user-images.githubusercontent.com/26483208/92366438-717ea380-f0f5-11ea-91f4-dce805cc98ae.png)

**Comment by salarenko** [comment]
- [ ] Missing form styles in Busy Indicator example - general
![image](https://user-images.githubusercontent.com/17496353/92375262-2ec2c880-f101-11ea-9fa4-31e138450d3b.png)

- [ ] Remove crash notifications (not relevant) - general
![image](https://user-images.githubusercontent.com/17496353/92377817-0a68eb00-f105-11ea-9617-4fe025b3455e.png)
![image](https://user-images.githubusercontent.com/17496353/92380090-d5f72e00-f108-11ea-88ba-6be9f0cbec84.png)

- [ ] Broken styles in "Combobox with Two Columns" and "Reactive Form" - general
![image](https://user-images.githubusercontent.com/17496353/92378176-ae529680-f105-11ea-8570-4fde1ab0ff9c.png)

![image](https://user-images.githubusercontent.com/17496353/92378233-c62a1a80-f105-11ea-8562-2c04c57eeb93.png)

- [ ] Documentation page has a stroke when loading and interacting with DateTime picker examples - IE11

- [ ] Broken headers in Dialog examples - general
![image](https://user-images.githubusercontent.com/17496353/92378922-d55d9800-f106-11ea-9115-c16639e22d4d.png)

- [ ] Complex Dialog example missing list selected styles - gneral
![image](https://user-images.githubusercontent.com/17496353/92379024-063dcd00-f107-11ea-8cc6-850629a9a5c7.png)

- [ ] Misaligned info label - general
![image](https://user-images.githubusercontent.com/17496353/92379269-78161680-f107-11ea-8014-ca5f07bcac42.png)

- [ ] List drag and broken (duplicates list items?) Also missing styles on dragged. Inspect console to find errors - IE11
![image](https://user-images.githubusercontent.com/17496353/92379519-e78c0600-f107-11ea-9652-708e2797936b.png)

- [ ] Popover misaligned example
![image](https://user-images.githubusercontent.com/17496353/92379987-a9431680-f108-11ea-8f20-4896a7d6dc0d.png)

- [ ] Space between select control and message
![image](https://user-images.githubusercontent.com/17496353/92380240-1787d900-f109-11ea-82ed-c661a6e95960.png)
 
- [ ] Broken layout of select extended options example
![image](https://user-images.githubusercontent.com/17496353/92380280-32f2e400-f109-11ea-8b43-d3e8a537e2f0.png)

- [ ] Shellbar broken button styling
![image](https://user-images.githubusercontent.com/17496353/92380330-4e5def00-f109-11ea-9cd6-86c5e90ae7b7.png)

- [ ] Broken layout of side navigation with icons examples
![image](https://user-images.githubusercontent.com/17496353/92380396-6a619080-f109-11ea-8fbc-f9df42c30239.png)

- [ ] Table with sorting broken popover layout
![image](https://user-images.githubusercontent.com/17496353/92380577-b7ddfd80-f109-11ea-8af5-eb03bbcd2b1e.png)

- [ ] No text wrapping in Feed Tile
![image](https://user-images.githubusercontent.com/17496353/92380825-13a88680-f10a-11ea-8443-ec4ec5a0033b.png)

**Comment by JKMarkowski** [comment]
- [ ] Warning on Application using ngx library
 ![image](https://user-images.githubusercontent.com/26483208/92388627-e7940200-f117-11ea-8fe0-e2d47771a967.png)
