### ISSUE TITLE
Defect Hunting Fundamental NGX 0.22

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#3086]
Test the platform lib and doc website. Log the issues here:
 - [ ] __Platform__ input alignment - https://fundamental-ngx.netlify.app/#/platform/input - looks like there is a missing styling - @Lokanathan-k , to be fixed.

RE: will be fixed as part of the PR https://github.com/SAP/fundamental-ngx/pull/3221 and PR https://github.com/SAP/fundamental-ngx/pull/3247

![Screen Shot 2020-09-02 at 7 59 29 PM](https://user-images.githubusercontent.com/4380815/92048901-d4b7b100-ed56-11ea-80ce-3726d49a5194.png)

- [ ] __Platform__ input with menu - styling issue https://fundamental-ngx.netlify.app/#/platform/input (Kevin - #3192)
![Screen Shot 2020-09-02 at 8 01 59 PM](https://user-images.githubusercontent.com/4380815/92049029-3d9f2900-ed57-11ea-94b2-86c47b402d33.png)

- [ ] __Platform__ inverted link example has a wrong background - Deepak, to be fixed
Fix provided in https://github.com/SAP/fundamental-ngx/pull/3226

![Screen Shot 2020-09-02 at 8 03 25 PM](https://user-images.githubusercontent.com/4380815/92049099-70492180-ed57-11ea-86b0-b2741db4185b.png)
an example how it should be
https://fundamental-ngx.netlify.app/#/core/link#basic 
![Screen Shot 2020-09-02 at 8 04 18 PM](https://user-images.githubusercontent.com/4380815/92049154-9ff82980-ed57-11ea-9d69-73bd3d60b644.png)

- [x] __Platform__ menu doesn't scroll - https://fundamental-ngx.netlify.app/#/platform/menu (Kevin - #3195)
![platform-menu](https://user-images.githubusercontent.com/4380815/92049351-2f9dd800-ed58-11ea-95d8-2d48ff6ab3fc.gif)
in core how it works
![core-menu](https://user-images.githubusercontent.com/4380815/92049441-7d1a4500-ed58-11ea-9337-1a5017603c7b.gif)

- [ ] __Platform__ menu button position is wrong https://fundamental-ngx.netlify.app/#/platform/menu-button
Fix provided in https://github.com/SAP/fundamental-ngx/pull/3231

![Screen Shot 2020-09-02 at 8 13 26 PM](https://user-images.githubusercontent.com/4380815/92049589-da15fb00-ed58-11ea-9eec-4be99759aea7.png) - to be fixed.

- [ ] __Platform__ search field on button hover has wrong styling https://fundamental-ngx.netlify.app/#/platform/search-field
![Screen Shot 2020-09-02 at 8 21 42 PM](https://user-images.githubusercontent.com/4380815/92050035-05e5b080-ed5a-11ea-9b04-37a9a686e386.png)
It has to be something like 
![Screen Shot 2020-09-02 at 8 21 55 PM](https://user-images.githubusercontent.com/4380815/92050082-29106000-ed5a-11ea-8c04-566262f44864.png) - @KevinOkamoto - #3237 

- [ ] __Platform__ Search field suggestion has 2 menus that are overlapping https://fundamental-ngx.netlify.app/#/platform/search-field
![search-field](https://user-images.githubusercontent.com/4380815/92050422-9623f580-ed5a-11ea-8d21-b285f35d8e8e.gif) -  (Kevin - #3237)

- [ ] __Platform__ Split Menu button doesn't work per spec - https://fundamental-ngx.netlify.app/#/platform/split-menu-button
Fix provided in https://github.com/SAP/fundamental-ngx/pull/3230

![broken-platform-split](https://user-images.githubusercontent.com/4380815/92052264-3f6aeb80-ed5b-11ea-9866-8ad83725408f.gif)
It should behave like
![split-menu](https://user-images.githubusercontent.com/4380815/92052351-45f96300-ed5b-11ea-9a6f-c058177bf74e.gif) - Deepak, to be fixed

- [ ] __Platform__ Step Input manual entry doesn't seem to work https://fundamental-ngx.netlify.app/#/platform/step-input @dimamarksman #3234 
![stepinput](https://user-images.githubusercontent.com/4380815/92053467-b0120800-ed5b-11ea-90fe-c3dad4020763.gif)

- [ ] __Platform__ Step Input validation appears on every other change https://fundamental-ngx.netlify.app/#/platform/step-input
![stepinput-validation](https://user-images.githubusercontent.com/4380815/92054740-24e54200-ed5c-11ea-84d6-4af9e3b2ca09.gif) - @dimamarksman, to be fixed. onChange should update the component with the changed value #3234 

- [ ] __Platform__ textarea width  issue - https://fundamental-ngx.netlify.app/#/platform/textarea (Kavya- #3221) 
![Screen Shot 2020-09-02 at 8 39 21 PM](https://user-images.githubusercontent.com/4380815/92055917-7ab9ea00-ed5c-11ea-9bc1-439d3b4128e2.png)

- [ ] __Platform__ textarea examples seems corrupted - https://fundamental-ngx.netlify.app/#/platform/textarea (Kavya- #3221) 
![Screen Shot 2020-09-02 at 8 40 17 PM](https://user-images.githubusercontent.com/4380815/92056255-96bd8b80-ed5c-11ea-85b6-56d129c21daf.png) - to be fixed

 - [ ] __Platform__ Panel on load give below error in console. - Valor, to be fixed  Artur #3224 
`libs/core/src/lib/toolbar/toolbar.component.ts.ToolbarComponent._getSortedByPriorityAndGroupItems
`

 - [ ] __Platform__ TextArea on load give below error in console - to be fixed (Kavya- #3221) 
```
main.js:24086 ERROR TypeError: Cannot read property ‘value’ of undefined 
    at TextAreaComponent.push.../../libs/platform/src/lib/components/form/text-area/text-area.component.ts.TextAreaComponent._getContentLength (2.js:49159).
```

- [ ] __Platform__ Radio Button Group
  tested on PR netlify https://deploy-preview-3036--fundamental-ngx.netlify.app/#/platform/radio-group
- Already fixed and merged to master. 
- on page load focus directly goes to a particular radio button
![2020-09-03_17-34-14 (1)](https://user-images.githubusercontent.com/53509521/92112668-c8d9f680-ee0b-11ea-87ae-8835bfeb8cf2.gif) - not reproducible. 

- [ ] __Styles__ Radio Button
- not sure if it is my eyes, but the selected dot in the radio button looks off-center randomly - Deepak, to be fixed
Issue raised for tracking: https://github.com/SAP/fundamental-styles/issues/1589
fixed in PR https://github.com/SAP/fundamental-styles/pull/1592

![2020-09-03_17-23-33](https://user-images.githubusercontent.com/53509521/92111921-a4314f00-ee0a-11ea-957e-cb2e5aaef9cc.gif)

- [ ] __Platform__ Search Field - to be fixed(Kevin - #3237).
- seems the search input is modifying the results and is also case sensitive when camelcasing is part of the word, for eg; a word like `Red Wagon` searched as `red` shows up `RedWagon`(removes the space) and consequently typing `redw` doesn't show up `RedWagon` although the list now has `RedWagon`. Is this expected?
![2020-09-03_17-43-02 (1)](https://user-images.githubusercontent.com/53509521/92113818-831e2d80-ee0d-11ea-870b-f0ca47227ac3.gif)
- when long list of data is present and you search a substring, the result popover does not stick to the search field and instead floats.
![2020-09-03_17-49-22 (1)](https://user-images.githubusercontent.com/53509521/92114333-46066b00-ee0e-11ea-9a67-a4fdca760af9.gif)

- [ ]__ Platform__Panel Windows Machins in the e
-  Platform Panel component with Actions example 
There is no space between the action buttons in the Panel with Actions Example. - Valor, to be fixed Artur #3224

![Annotation 2020-09-04 150936](https://user-images.githubusercontent.com/53512176/92225580-06e52200-eec1-11ea-8bc8-d0949af3c31a.png)

**Comment by sKudum** [comment]
- [ ] __Platform__ Panel on load give below error in console.
libs/core/src/lib/toolbar/toolbar.component.ts.ToolbarComponent._getSortedByPriorityAndGroupItems


 - [ ] __Platform__ TextArea on load give below error in console

main.js:24086 ERROR TypeError: Cannot read property ‘value’ of undefined
    at TextAreaComponent.push.../../libs/platform/src/lib/components/form/text-area/text-area.component.ts.TextAreaComponent._getContentLength (2.js:49159).

**Comment by olshansky** [comment]
- [ ] **Platform** - Menu Button - incorrect popover position 

fundamental-ngx: 
![menu-button-ngx](https://user-images.githubusercontent.com/14160094/92116217-39791700-edfc-11ea-8bae-514126d4306c.gif)

sapui5:
![menu-button-sapui5](https://user-images.githubusercontent.com/14160094/92116263-472e9c80-edfc-11ea-8891-4808234a7f6b.gif)

_____

- [ ] **Platform** - Menu Button - stackblitz works incorrect
![stackblitz](https://user-images.githubusercontent.com/14160094/92116486-91b01900-edfc-11ea-86e7-9c6a0a0b09eb.gif)

**Comment by DeepakSap14** [comment]
- [ ] Info-label:
Info-label with only icon does not fall inline. vertical alignments gets shifted.
<img width="1126" alt="Info-label" src="https://user-images.githubusercontent.com/57661487/92120412-a4cfe280-ee16-11ea-85e7-030661761e29.png">

- [ ] Objects status.
icon also gets underlined. Even if some other object-status is hovered, some other other object-status icon gets undeined.



![object-status](https://user-images.githubusercontent.com/57661487/92122014-94206c00-ee18-11ea-97ac-c4ec328faf4c.gif)

**Comment by puru-hk** [comment]
Theming is not working for IE and Edge browser (windows).

![image](https://user-images.githubusercontent.com/32538291/92131014-11e97500-ee23-11ea-8d4a-e28eb59755b6.png)

**Comment by puru-hk** [comment]
Infolabel In RTL mode  header is not aligned. 

RTL mode 

![image](https://user-images.githubusercontent.com/32538291/92134712-7c9caf80-ee27-11ea-96fa-a46afe2503e4.png)


Normal mode


![image](https://user-images.githubusercontent.com/32538291/92134649-6a227600-ee27-11ea-8dcd-7ce8c64b31e7.png)

**Comment by puru-hk** [comment]
Link: Tooltip is not showing for truncated text.

[Link tooltip for truncated text .zip](https://github.com/SAP/fundamental-ngx/files/5169794/Link.tooltip.for.truncated.text.zip)

**Comment by droshev** [comment]
> Theming is not working for IE and Edge browser (windows).
> 
> ![image](https://user-images.githubusercontent.com/32538291/92131014-11e97500-ee23-11ea-8d4a-e28eb59755b6.png)

That is fine as we use CSS variables which are not supported in IE11

**Comment by puru-hk** [comment]
Menu border is not proper in IE browser. 

![image](https://user-images.githubusercontent.com/32538291/92225542-f6cd4280-eec0-11ea-9c03-45105b504ffd.png)

**Comment by puru-hk** [comment]
Tooltip is not shown for all the menu button and also truncated text. 
[Tooltip is not showing for Menu button .zip](https://github.com/SAP/fundamental-ngx/files/5174008/Tooltip.is.not.showing.for.Menu.button.zip)

**Comment by manu-kr** [comment]
- [ ]__ Platform__Panel Windows Machins in the e
-  Platform Panel component with Actions example 
There is no space between the action buttons in the Panel with Actions Example.

![Annotation 2020-09-04 150936](https://user-images.githubusercontent.com/53512176/92225580-06e52200-eec1-11ea-8bc8-d0949af3c31a.png)

**Comment by puru-hk** [comment]
Radio button group tab order is not working. 

[Tab order is not working.zip](https://github.com/SAP/fundamental-ngx/files/5174171/Tab.order.is.not.working.zip)

**Comment by manu-kr** [comment]
**(Windows) Platform Input Component**

- Input of Type Number is accepting string value in IE browser. 

![number-input](https://user-images.githubusercontent.com/53512176/92228940-511cd200-eec6-11ea-8880-1a6714eeb4b2.png)

- Input box width is not 100% in IE .
 **Actual**
![number-input](https://user-images.githubusercontent.com/53512176/92229085-8cb79c00-eec6-11ea-93e5-f6ee6a1d1fc9.png)

Expected:
![input-width](https://user-images.githubusercontent.com/53512176/92229654-6f370200-eec7-11ea-9493-00450b23a706.png)

**Comment by puru-hk** [comment]
Search Filed: Without entering the letter or character autosuggestion is showing. And entering the space bar auto suggestion is showing. 

![image](https://user-images.githubusercontent.com/32538291/92229648-6cd4a800-eec7-11ea-869c-1c8fd5225f97.png)

**Comment by puru-hk** [comment]
Input : Using keyboard cannot select the auto suggestion result. 

![image](https://user-images.githubusercontent.com/32538291/92232165-b1624280-eecb-11ea-921b-02f0e48fe027.png)

**Comment by puru-hk** [comment]
Split Menu Button: Alignment is not proper in RTL mode in IE browser.

RTL mode
![image](https://user-images.githubusercontent.com/32538291/92232447-2f264e00-eecc-11ea-8fae-46c8a1adec77.png)

Normal Mode

![image](https://user-images.githubusercontent.com/32538291/92232532-4e24e000-eecc-11ea-9195-caa11111dbad.png)

**Comment by puru-hk** [comment]
Search Field: Category is not closing even after selected the category from the keyboard. 
[Category is not closing even after selected.zip](https://github.com/SAP/fundamental-ngx/files/5174443/Category.is.not.closing.even.after.selected.zip)

**Comment by puru-hk** [comment]
Step Input : Inline value hep is not required for step input. 

![image](https://user-images.githubusercontent.com/32538291/92233552-1d45aa80-eece-11ea-9947-0e457decaf05.png)

**Comment by puru-hk** [comment]
Step Input is accepting the characters. 

![image](https://user-images.githubusercontent.com/32538291/92233746-74e41600-eece-11ea-9c3e-8cc9c555d1c4.png)

**Comment by puru-hk** [comment]
Style is not proper for switch toggle button in IE browser. 

![image](https://user-images.githubusercontent.com/32538291/92234289-5f232080-eecf-11ea-926e-b93fd426af80.png)

**Comment by puru-hk** [comment]
Textarea not able to see the text properly.

![image](https://user-images.githubusercontent.com/32538291/92234651-0b650700-eed0-11ea-8872-747e16c624a6.png)

**Comment by puru-hk** [comment]
Text area style are not proper in windows machine for all the browsers. 

![image](https://user-images.githubusercontent.com/32538291/92234948-85958b80-eed0-11ea-8209-eaebcd616215.png)

**Comment by manu-kr** [comment]
**(Windows)Platform Checkbox component **
Focus for the checkbox is taking full width in IE . It should select only label and checkbox.
Actual:

![focus-width](https://user-images.githubusercontent.com/53512176/92252512-f5653f80-eeeb-11ea-82be-3971c0478268.png)

Expected:
![chrome-focus](https://user-images.githubusercontent.com/53512176/92252920-8805de80-eeec-11ea-8391-f32e616bbac6.png)

**Comment by olshansky** [comment]
# Safari 13.1.2

- [ ] **Platform** - Textarea - when going to textarea documntation page it throw Error `TypeError: undefined is not an object (evaluating 'this.textareaElement.nativeElement.value')`
![image](https://user-images.githubusercontent.com/14160094/92372574-d2ae7300-f105-11ea-8c1e-ae8aeaca89cb.png)

_____

- [ ] **Platform** - Textarea - documentation is broken 
![textarea](https://user-images.githubusercontent.com/14160094/92379057-75b7ba80-f10f-11ea-94b0-0b0dd0386aa9.gif)

_____

**Comment by manjunathanagaraj** [comment]
> Search Field: Category is not closing even after selected the category from the keyboard.
> [Category is not closing even after selected.zip](https://github.com/SAP/fundamental-ngx/files/5174443/Category.is.not.closing.even.after.selected.zip)

**Comment by dimamarksman** [comment]
> Step Input is accepting the characters. Valor, to be fixed @dimamarksman #3234
> 
> ![image](https://user-images.githubusercontent.com/32538291/92233746-74e41600-eece-11ea-9c3e-8cc9c555d1c4.png)

@puru-hk actually that's by design.
https://app.gitbook.com/@fundamental-ngx/s/docs/v/master/platform-step-input-1
> If the user enters an invalid value, the invalid value remains in the input field. An error state is displayed.

When `step-input` can not parse entered value it sets `value` to null.
If step input is used withing a form and `formField` is required it will lead to `required error`, cause null will be considered as an empty filed.
Please see the example https://fundamental-ngx.netlify.app/#/platform/numberStepInput#templateDrivenForm.

**Comment by puru-hk** [comment]
When we do the tab order focus is not able to see for radio button button for button we are able to see the focus for all the browser in windows machine. 

[Focus is not able to see for tab order.zip](https://github.com/SAP/fundamental-ngx/files/5194616/Focus.is.not.able.to.see.for.tab.order.zip)

**Comment by KevinOkamoto** [comment]
> Menu border is not proper in IE browser. - @KevinOkamoto , to be fixed.
> 
> ![image](https://user-images.githubusercontent.com/32538291/92225542-f6cd4280-eec0-11ea-9c03-45105b504ffd.png)

@puru-hk This is a fundamental-styles issue. Please create issue in fundamental-styles.

**Comment by puru-hk** [comment]
> Radio button group tab order is not working.
> 
> And In IE and firefox browser - @DeepakSap14 , to be fixed.
> 
> Tested in this url. https://deploy-preview-3036--fundamental-ngx.netlify.app/#/core/radio
> 
> [Tab order is not working.zip](https://github.com/SAP/fundamental-ngx/files/5174171/Tab.order.is.not.working.zip)
> 
> * Need further clarification. -- Deepak

This has been explained
