### ISSUE TITLE
Card support and improvements

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5142]
- [ ] Review styles implementation against the latest design
- [ ] Revisit the ngx implementation - it seems that there are differences between ngx and styles
- [ ] OVP Resizable Layout
- [ ] check integration and adaptive cards
