### ISSUE TITLE
Graphs and Charts support

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5143]
Review, analyze, and summarize:
- [ ] [highcharts](https://www.npmjs.com/package/highcharts) [link](https://www.highcharts.com/blog/)
- [ ] [ng-apexcharts](https://www.npmjs.com/package/ng-apexcharts)
- [ ] [chartjs](https://github.com/chartjs/Chart.js)
- [ ] [ngx-charts](https://swimlane.gitbook.io/ngx-charts/)

Review Fiori 3 specs for graphs, charts, and theming support

**Comment by droshev** [comment]
- [ ] PoC review the 4 libraries above and compare them

**Comment by N1XUS** [comment]
After investigation I've created a comparison table with general features:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e39d10c2-7fff-441f-015f-3df452e67070"><div dir="ltr" style="margin-left:0pt;" align="center">

Feature | Highcharts | Chartjs | Apexcharts | ngx-charts
-- | -- | -- | -- | --
License | Commercial | MIT | MIT | MIT
Angular wrapper | ✓ | ✓ | ✓ | ✓
Weekly npm downloads | 621 715 | 1 466 973 | 230 177 | 109 006
Unique chart types | 30+ | 8 | 25+ | 9
Theming | ✓ | ✓ | ✓ | ✓
Custom chart types | x | ✓ | x | ✓

</div></b>

On my opinion apexcharts and chartjs are best-fitted libraries to use

**Comment by ibakshay** [comment]
Hi @N1XUS, 
Thank you for doing the research and analysis. 
I am from SAP Dora team. We will be using Fundamental NGX extensively and I was wondering if there will be a **graph** and **chart** native support from `fundamental-ngx` library?

**Comment by SchwalmM** [comment]
Is there any Update on that topic? We also would really like to use charts in our fundamental based project.

**Comment by droshev** [comment]
@SchwalmM unfortunately we didn't have any bandwidth to investigate into that direction yet. Any ideas or suggestions from your end?
