### ISSUE TITLE
NGX Doc and API improvements

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5144]
- [ ] Review the current examples
- [ ] Review the current Doc API - there are some glitches (e.g. Table components in platform)
- [ ] consider improving the build (aggressive caching to minimize the build time)
- [ ] hot module replacement
- [ ] focus on Development Experience - improve the current examples, identify improvements
