### ISSUE TITLE
DXP Support

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5279]
- [x] Bring platform table in template UI - TODO(add custom width in ngx-platform table)
- [x] Form Generation - #5263
- [ ] Table improvements and new features - ngx #5280
- [ ] Table pagination - align with GraphQL (including sorting, filtering)
- [x] Template UI update - # 432 (List floorplan) - the only 'component' we are missing is filter bar and there is not proper design. TBD
- [x] i18n - next steps -> document and review with core team
- [x] Time format - # 475
- [x] no content page - # 478 - check with Colin
- [ ] enable strict mode
- [x] Pagination - tbd
- [x] error screens - # 479
- [x] Notification Center - # 465
