### ISSUE TITLE
DXP Support - sprint 63

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5411]
- [x] Bring platform table in template UI - TODO(add custom width in ngx-platform table)
- [x] Table improvements and new features - ngx #5280
- [ ] Table pagination - align with GraphQL (including sorting, filtering)
- [x] i18n - next steps -> document and review with core team
- [x] no content page - # 478 - check with Colin
- [ ] enable strict mode
- [ ] Pagination - tbd
- [ ] error screens - # 479
- [ ] Notification Center - # 465
