### ISSUE TITLE
List Floorplan

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5639]
List Floorplan comes with variety of features inside:
- [x] with/without Variant management - check [this](https://github.com/SAP/fundamental-ngx/pull/4563) out
- [x] simple and complex filtering(allow a dialog for selecting more/less fields for filtering)
- [x] live and manual filter
- [x] collapsed and expanded page
- [x] table features
  - export/export as
  - fiori moments for no entries/no search result
  - delete/edit data
  - pagination
- [x] flex column layout(FCL) from the table when there is a navigation
- [x] allow edit the object page - this is navigation from FCL to Object Page

Links to review 
- [x] https://experience.sap.com/fiori-design-web/list-report-floorplan-sap-fiori-element/
- [x] https://sapui5.hana.ondemand.com/#/topic/1cf5c7f5b81c4cb3ba98fd14314d4504

**Comment by N1XUS** [comment]
Closing, since all checkboxes are checked.
