### ISSUE TITLE
Overview Page Layout

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#5641]
- [ ] variant management - user can save an updated view in a variant
- [ ] header collapsed/expanded
- [ ] badges on cards, 
- [ ] analytical, list, bar chart list, table, stack, quick view cards
- [ ] toolbar - edit page (very rare action)
- [ ] overlay on the cards - disable clicking on the cards, menu btn on the top right corner, no variant management available
- [ ] edit on the card opens a dialog - 2 sides - left for the metadata, right - preview
- [ ] cards with resize icon and able to resize
- [ ] rearrange the cards
- [ ] add new card happens in edit more, open a dialog with list of the available, tabs to filter and sort. once the user selects it goes to screen like edit cards
- [ ] column grid(based on CSS grid) - from 1 to 12, 16, 20. The user can resize between 1 to 12/16/columns
- [ ] support resizable cards and drag-and-dropping - nice to have feature
