### ISSUE TITLE
feat(core,platform): allow to select ranges in components with multi-selection using "shift"

### ISSUE THREAD

**Issue by dmitry-stepanenko** [SAP/fundamental-ngx#7618]
An ability to select ranges is not implemented in controls, that support multi-selection:
- [x] core-multi-input
- [x] core-grid-list
- [ ] core-standard-list
- [x] core-table
- [ ] core-upload-collection
- [ ] platform-approval-flow (edit mode)
- [ ] platform-checkbox-group
- [ ] platform-list
- [ ] platform-multi-combobox
- [ ] platform-table
- [ ] platform-upload-collection

Additionally under that epic should verify each of these components that has "select all" feature, supports indeterminate state of "select all" toggle
