### ISSUE TITLE
Horizon 2023 Project

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-ngx#9823]
List of components to be created/updated:
- [x] **bring Angular 16** - This is in separate ticket
- [x] Avatar #9825 - https://github.com/SAP/fundamental-ngx/pull/10553
- [x] Avatar Group #9826
- [x] Busy Indicator #9827
- [x] Buttons (Standard, Menu Button, Split Button, Segmented Button, Toggle Button) #9828
- [x] Calendar/Date picker/Date Time picker #9829 - https://github.com/SAP/fundamental-ngx/pull/10324
- [x] Card #9831
- [x] Carousel  #9821 - https://github.com/SAP/fundamental-ngx/pull/10274
- [x] Checkbox #9832 - https://github.com/SAP/fundamental-ngx/pull/10315
- [x] Combobox #9833 - no changes needed
- [x] Dialog #9834 - https://github.com/SAP/fundamental-ngx/pull/10569
- [x] Dynamic Page #9835 - no changes needed
- [x] Dynamic Side Content #9836 - no changes needed
- [x] Flexible Column Layout #9838 
- [x] Icon Tab Bar #9839
- [x] Input #9840 
- [x] Label #9841 - no changes required
- [x] Link #9842
- [x] List #9843
- [x] Menu #9844
- [x] Message Strip #9845
- [x] Multi Combobox #9846
- [x] Multi Input #9847 - no changes needed
- [x] Page #9848 - no changes needed
- [x] Popover #9849
- [x] Progress Indicator #9850
- [x] Radio Button #9851
- [x] Shell #9852 - https://github.com/SAP/fundamental-ngx/pull/10275
- [x] Select #9853
- [x] Sllider and Range Slider #9854 - Denis
- [x] Step Input #9855
- [x] Switch #9856
- [x] Table #9857 - no changes needed
- [x] Tag #9858
- [x] Textarea #9859
- [x] Tile #9860 - no changes needed
- [X] Title #9861 - no changes needed
- [x] Toolbar #9824 - https://github.com/SAP/fundamental-ngx/pull/10314

New Design Changes:
- [x] Splitter #9890 - no changes needed
- [x] Message Popover #9889 - https://github.com/SAP/fundamental-ngx/pull/10317
- [x] Panel #9896
- [x] Token and Tokenizer #9920
- [x] Object Status #10070 - https://github.com/SAP/fundamental-ngx/pull/10539
- [x] Bar

BTP 
- [ ] BTP Duplicated Components strategy 
- [ ] BTP Search 
- [ ] BTP Notification 
- [ ] BTP Tool Layout 
- [ ] BTP Vertical Navigation 
- [ ] BTP Horizontal Nav 
- [ ] BTP Tool Header 
- [ ] BTP Menu 
- [ ] BTP Button in Tool Header 
- [ ] BTP User Menu 
- [ ] BTP Info Label
